### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by TheWillard** [gruppe-adler/grad_aff#1]
* Main
  * StreamUtil
    * [x] Dedicated class based on Boost.Iostreams
      * [x] Should handle all of the weird BIS data structures
    * [ ] Boost.Iostreams custom implementations
      * [x] [COM IStream](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-istream)
      * [ ] [GFile](https://developer.gnome.org/gio/stable/GFile.html) (required for GIMP3)
  * [ ] directory refactor
  * [ ] C API 
  * [ ] better API/Helper Methods
  * [ ] lzo mt refactor
  * [ ] better error/exception handling

* Modules
  * paa
    * [x] partial loading
  * pbo
    * [ ] more efficent loading
    * [ ] sha1 calculation in stream
    * [ ] better api
  * rap
    * [ ] pegtl parser refactor
    * [ ] array fix
    * [ ] preprocessor (clang?)
  * p3d
    * [ ] refactor/complete implementation (read)
  * wrp
    * [ ] multithreading for slow lzo stuff

* CMake
  * [ ] refactor
  * [ ] modularize file formats
  * [ ] options for optional dependencies

* Docs
  * [ ] CMake build
  * [ ] Documentation
  * [ ] Github.io page
  * [ ] Build

* CI
  * [ ] various builds
  * [ ] tests
  * [ ] automated releases
  * [ ] codecv/codecov?

* [ ] vcpkg package
  * [ ] fix emscripten for deps

* [ ] logo

**Comment by DerZade** [comment]
![](https://media3.giphy.com/media/b1o4elYH8Tqjm/giphy.gif?cid=ecf05e47lnv9v14p17kvqoj5z76xw720x9hnrtvbbapfmljt&rid=giphy.gif)
